server:
  port: 9000

spring:
  # 数据库配置
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@120.77.80.134:1521:orcl
    username: shareimage
    password: 123456
    # 连接池
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
#      connection-test-query: SELECT 1
#      validationQuery: SELECT * from dual
      connection-test-query: SELECT * from dual

mybatis:
  mapper-locations: classpath:/mapping/*Mapper.xml
#  type-aliases-package: com.guet.shareimage.bean.pojo

logging:
  level:
    com.guet.shareimage.mapper: debug